version: "3.7"
services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspaces/d5-solitaire
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DISPLAY=${DISPLAY}
    command: sleep infinity
