version: "3.7"
services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspaces/d5-solitaire
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sleep infinity
