# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    # container:
    #   image: ghcr.io/kanamexx/devcontainer:latest
    #   credentials:
    #     username: kanamexx
    #     password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        continue-on-error: true
      - name: Upload VRT diff
        uses: actions/upload-artifact@v3
        with:
          name: VRT-diff
          path: ./src/client/__image_snapshots__/__diff_output__/visual-regression-test-test-tsx-visualization-components-have-appropriate-visual-1-diff.png
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
