# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    environment: CI
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kanamexx/devcontainer:latest
      credentials:
        username: kanamexx
        password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
      volumes:
        - /tmp/.X11-unix/:/tmp/.X11-unix/
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: "npm"
      - run: npm install
      - run: npm ci
      # - run: pwd
      # - run: ls / -la
      # - run: ls /__w/ -la
      # - run: ls /__w/d5-solitaire/ -la
      # - run: ls /__w/d5-solitaire/d5-solitaire/ -la
      - run: chmod a+w -R ./dist
      # - run: sudo npm run build
      - run: npm run build --if-present
      - run: sudo npm test
        continue-on-error: true
      - name: Upload VRT diff
        uses: actions/upload-artifact@v3
        with:
          name: VRT-diff
          path: ./src/client/__image_snapshots__/__diff_output__/
