# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    environment: CI
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kanamexx/devcontainer:latest
      credentials:
        username: kanamexx
        password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
      volumes:
        - /:/__w/d5-solitaire
        - /tmp/.X11-unix/:/tmp/.X11-unix/
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm ci
      - run: chmod a+w -R ./dist
      - run: npm run build --if-present
      - run: sudo npm test
      - name: Upload VRT diff
        if: failure() && stemps.fail_step.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: VRT-diff
          path: ./src/client/__image_snapshots__/__diff_output__/
